#!/usr/bin/env bash

abspath=$(readlink -e $(dirname $0))
cd $abspath

exec 2>&1
for pdf in `ls Scenarios/*.pdf`; do
  dir_name=`basename "${pdf%.*}"`
  if [[ ! -d Scenarios/$dir_name ]]; then
    /usr/local/bin/bundle exec ./bin/extract -ic $pdf
  fi
done
