#!/usr/bin/env bash

abspath=$(readlink -e $(dirname $0))
cd $abspath

options=${1:-"mic"}

bundle=`which bundle`
if [[ ! -x $bundle ]]; then
  bundle=/user/local/bin/bundle
fi

exec 2>&1
for pdf in `ls Scenarios/*.pdf`; do
  dir_name=`basename "${pdf%.*}"`
  if [[ ! -d Scenarios/$dir_name ]]; then
    $bundle exec ./bin/extract -$options $pdf
  fi
done
